### ML Model(Logistic Regression) with Rule based Heuristics

In [2]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [3]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [4]:
df = pd.read_csv("fake_job_postings.csv")
df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  str
 2   location             17534 non-null  str
 3   department           6333 non-null   str
 4   salary_range         2868 non-null   str
 5   company_profile      14572 non-null  str
 6   description          17879 non-null  str
 7   requirements         15184 non-null  str
 8   benefits             10668 non-null  str
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  str
 13  required_experience  10830 non-null  str
 14  required_education   9775 non-null   str
 15  industry             12977 non-null  str
 16  function             11425 non-null  str
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), str(13)
memory usage: 2.5 MB

In [6]:
df['fraudulent'].value_counts()

fraudulent
0    17014
1      866
Name: count, dtype: int64

In [7]:
df=df[['description','fraudulent']]
df.head()

                                         description  fraudulent
0  Food52, a fast-growing, James Beard Award-winn...           0
1  Organised - Focused - Vibrant - Awesome!Do you...           0
2  Our client, located in Houston, is actively se...           0
3  THE COMPANY: ESRI – Environmental Systems Rese...           0
4  JOB TITLE: Itemization Review ManagerLOCATION:...           0

In [8]:
df.dropna(inplace=True)

In [13]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    
    return " ".join(tokens)

In [14]:
df['cleaned_text'] = df['description'].apply(clean_text)

In [16]:
df.head()

,description,fraudulent,cleaned_text
0,"Food52, a fast-growing, James Beard Award-winn...",0,food fast growing james beard award winning on...
1,Organised - Focused - Vibrant - Awesome!Do you...,0,organised focused vibrant awesome passion cust...
2,"Our client, located in Houston, is actively se...",0,client located houston actively seeking experi...
3,THE COMPANY: ESRI – Environmental Systems Rese...,0,company esri environmental systems research in...
4,JOB TITLE: Itemization Review ManagerLOCATION:...,0,job title itemization review managerlocation f...

In [17]:
vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df['cleaned_text']).toarray()
y = df['fraudulent']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [22]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9675615212527964
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      3394
           1       1.00      0.36      0.53       182

    accuracy                           0.97      3576
   macro avg       0.98      0.68      0.76      3576
weighted avg       0.97      0.97      0.96      3576

In [23]:
import pickle

pickle.dump(model, open("model/fake_job_model.pkl", "wb"))
pickle.dump(vectorizer, open("model/tfidf_vectorizer.pkl", "wb"))

In [24]:
def predict_job(text):
    text = clean_text(text)
    vector = vectorizer.transform([text])
    
    prediction = model.predict(vector)[0]
    confidence = model.predict_proba(vector)[0]
    
    if prediction == 1:
        result = "Fake Job"
        score = confidence[1]
    else:
        result = "Genuine Job"
        score = confidence[0]
    
    return result, score

In [25]:
predict_job("Earn money from home without experience")

('Fake Job', np.float64(0.5297687720626717))

In [28]:
scam_keywords = [
    "earn money fast",
    "work from home",
    "no experience required",
    "investment required",
    "limited seats",
    "urgent hiring",
    "click here",
    "pay registration fee",
    "easy money",
    "guaranteed income",
    "Too good to be true",
    "Urgent hire",
    "Immediate start",
    "No experience needed",
    "Earn $5000/week from home",
    "Guaranteed income",
    "Pay upfront fee",
    "Processing fee required",
    "Buy equipment/starter kit",
    "Wire transfer for training",
    "Performance-based pay only",
    "Rock star needed",
    "Unlimited earning potential",
    "Work hard, play hard",
    "Accelerated management path",
    "Easy tasks, high pay"
]
def rule_based_score(text):
    text = text.lower()
    
    score = 0
    
    for keyword in scam_keywords:
        if keyword in text:
            score += 1
            
    return score

In [30]:
def final_predict(text):
    cleaned = clean_text(text)
    vector = vectorizer.transform([cleaned])
    
    # ML Prediction
    ml_pred = model.predict(vector)[0]
    ml_prob = model.predict_proba(vector)[0]
    
    # Rule Score
    rule_score = rule_based_score(text)
    
    # Decision Logic
    if rule_score >= 2:
        return "Scam (Rule-Based)", 0.9
    
    elif ml_pred == 1:
        return "Scam (ML)", ml_prob[1]
    
    elif rule_score == 1:
        return "Caution", 0.5
    
    else:
        return "Genuine", ml_prob[0]

In [31]:
final_predict("Earn money fast from home, no experience required, limited seats!")

('Scam (Rule-Based)', 0.9)

In [32]:
def explain_prediction(text):
    reasons = []
    
    for keyword in scam_keywords:
        if keyword in text.lower():
            reasons.append(keyword)
            
    return reasons

In [33]:
explain_prediction("Earn money fast from home, no experience required, limited seats!")

['earn money fast', 'no experience required', 'limited seats']

In [ ]:
|